# initialize Redis connection settings
REDIS_HOST = "0.0.0.0"
REDIS_PORT = 6379
REDIS_DB = 0
WEB_REDIS_HOST = "192.168.1.70"
WEB_REDIS_PORT = 6379
WEB_REDIS_DB = 0
WEB_SERVER_HOST = "http://192.168.1.70"

# initialize constants used to control image spatial dimensions and
# data type
CNN_IMAGE_WIDTH = 540
CNN_IMAGE_HEIGHT = 540
CNN_IMAGE_CHANS = 3
CNN_IMAGE_DTYPE = "uint8"
CNN_IMAGE_FEATURE_FULL_SIZE = 2048
CNN_IMAGE_FEATURE_REDUCED_SIZE = 512

MTC_IMAGE_WIDTH = 700
MTC_IMAGE_HEIGHT = 700
MTC_IMAGE_CHANS = 1
MTC_IMAGE_DTYPE = "uint8"

# initialize constants used for server queuing
IMAGE_QUEUE = "image_queue"
BATCH_SIZE = 32
NR_RETR = 5
MAX_NR_RETR = 20
MTC_IMAGE_QUEUE = "matching_queue"
MTC_BATCH_SIZE = 2
FAISS_QUEUE = "faiss_queue"

SERVER_SLEEP = 0.05
CLIENT_SLEEP = 0.05

# initialize content keys
FILE_KEY = "file"
ID_KEY = "id"
IMAGE_KEY = "image"
IMAGE_WIDTH_KEY = "width"
IMAGE_HEIGHT_KEY = "height"
CNN_PRE_COMPUTED_KEY = "pre_computed_features"
SIMILAR_IMAGES_KEY = "similar_imgs"
SCORE_KEY = "score"
SCORE_MATCHES = "score_matches"
SHOP_ID_KEY = "shopid"
NR_RETR_KEY = "nr_retr"
APP_CODE_KEY = "app_code"
SALE_PRICE = "sale_price"
PURCHASE_PRICE = "purchase_price"
IMAGE_BOXES = 'box'
SHAPE_KEY = 'shape'
SOD_KEY = 'sod'
CATEGORIES_KEY = 'category'
SKU_CD = 'sku_cd'

# database config
DATABASE_LIST_PATH = "database_list.json"
DESC_MODE_CONFIG = "DESC_MODE"
TIME_BEGIN = "BEGIN_TIME"
TIME_END = 'END_TIME'
CATEGORY_FILE = "CATEGORY_FILE"
DICT_CATEGORY_LABEL = "DICT_CATEGORY2LABEL"
DICT_LABEL_CATEGORY = "DICT_LABEL2CATEGORY"
DATABASE_KEY = "DATABASE"
INDEX_FILE_KEY = "INDEX_FILE"
PCA_MATRIX_FILE_KEY = "PCA_MATRIX_FILE"
IMG_LIST_FILE_KEY = "IMG_LIST_FILE"
IMG_LIST_FILE_JSON_KEY = "IMG_LIST_FILE_JSON"
CNN_IMAGE_FEATURE_USING_PCA_KEY = "CNN_IMAGE_FEATURE_USING_PCA"
INDEX_NPROBE_KEY = 'INDEX_NPROBE'
MTC_IMAGE_DB_FOLDER_KEY = 'MTC_IMAGE_DB_FOLDER'
MTC_HIST_DB_FOLDER_KEY = 'MTC_HIST_DB_FOLDER'
MTC_DESCS_DB_FOLDER_KEY = 'MTC_DESCS_DB_FOLDER'
MTC_PRE_COMPUTED_KEY = 'MTC_PRE_COMPUTED'
MTC_FEATURE_KEY = 'MTC_FEATURE'
MTC_IS_NEED_HOMOGRAPHY_KEY = 'MTC_IS_NEED_HOMOGRAPHY'
MTC_USING_SUPERGLUE_KEY = 'MTC_USING_SUPERGLUE'
DICT_ITEM_CATEGORY = 'DICT_ITEM_CATEGORY'
API_KEY = 'API_KEY'
USE_CATEGORY = 'USE_CATEGORY'

# logger info
LOGGER_INFO_PATH = "logs/info"
LOGGER_ERROR_PATH = "logs/error"
LOGGER_CONF_NAME = "logger.conf"

# save query images
CBIR_SAVE_QUERY_IMAGES = True
QUERY_IMAGE_FOLDER = "query_images/"

# requests timeout
REQ_TIME_OUT = 5000

#
APP_DB_NAME = 'lashinbang_database'
KBOOK_UPDATE_PRICE_TOKEN = '60ae7201b5d44a0d'
MATHCHING_CONFIG = "CONFIG_MATCHING"

STATIC_FOLDER = ''

# url images server.
URL_IMAGE = 'https://test-la.anlab.info/api/get-raw-images'

#ConfigPrompt
SAVE_IMAGE_URL = 'SaveQuery/'
PROMPT_IMAGE_URL = '/media/anlab/data-2tb/ANLAB_THUY/ToyotaAR/Dataset/support1_black.jpg'